---

- hosts: servers_win

  vars:
    directorios: "{{ lookup('file','../archivos/directorios.txt').split('\n') }}"

  tasks:
    - name: Crea directorios
      ansible.windows.win_file:
         path: C:\{{ item }}
         state: directory
      with_items: "{{ directorios }}"

