---

- hosts: servers
  become_user: ubuntu

  tasks:
    - name: Borra directorios
      file:
         path: $HOME/{{ item }}
         state: absent
      with_items: [ 'uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis']



