---

- hosts: servers_win
  tasks:
    - name: Envia mensaje
      community.windows.win_msg:
        display_seconds = 60
        msg: Mensaje de prueba generado desde un pipeline en Jenkins usando Ansible a una VM Windows
